name: TestSuite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - run: |
       echo "Download & Install LuaJIT"
       sudo apt-get update -y
       sudo apt-get install -y luajit

    - run: |
       echo "Installed LuaJIT"
       luajit -v

    - name: Check out repository code
      uses: actions/checkout@v2
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

    - name: Switch to script files
      run: |
        cd "plugins/sasl/data/modules/Custom Module/tests/"
        luajit suite.lua
        
